from __future__ import annotations

from typing import List, TYPE_CHECKING

from components.base_component import BaseComponent
import random

if TYPE_CHECKING:
    from entity import Actor, Item


class Lore(BaseComponent):
    parent: Actor

    def __init__(self):
        self.previous_job = random.choice([
            "accountant",
            "actor",
            "administrative assistant",
            "anesthesiologist",
            "architectural engineer",
            "bank teller",
            "barista",
            "bartender",
            "butcher",
            "canvasser",
            "carpenter",
            "cashier",
            "civil engineer",
            "consultant",
            "cook",
            "custodian",
            "customer support rep",
            "data entry clerk",
            "delivery driver",
            "dental hygienist",
            "dishwasher",
            "dockworker",
            "dog walker",
            "drug dealer",
            "editor",
            "electrician",
            "embalmer",
            "event planner",
            "exterminator",
            "farmer",
            "financial advisor",
            "firefighter",
            "fisher",
            "flight attendant",
            "gas station attendant",
            "graphic designer",
            "grifter",
            "hair stylist",
            "hotel clerk",
            "housekeeper",
            "HR specialist",
            "insurance adjuster",
            "IT admin",
            "journalist",
            "laborer",
            "landscaper",
            "laundry worker",
            "Legislative aide",
            "librarian",
            "delivery driver",
            "mail carrier",
            "machinist",
            "market researcher",
            "masseuse",
            "mechanic",
            "miner",
            "musician",
            "nurse",
            "office clerk",
            "packager",
            "painter",
            "paralegal",
            "paramedic",
            "park ranger",
            "pawnbroker",
            "personal trainer",
            "pharmacy tech",
            "physical therapist",
            "pickpocket",
            "plumber",
            "project manager",
            "PR specialist",
            "radiologist",
            "real estate broker",
            "salesperson",
            "security guard",
            "sewer inspector",
            "shift supervisor",
            "social worker",
            "software developer",
            "stay-at-home parent",
            "stock clerk",
            "streamer",
            "subway worker",
            "teacher",
            "telemarketer",
            "trash collector",
            "truck driver",
            "union rep",
            "utility worker",
            "valet",
            "veterinarian",
            "video editor",
            "video game tester",
            "server at a restaurant",
            "welder",
            "Window washer",
            "writer",
            "yoga instructor",
            "zookeeper"
        ])
